/**
 * Created by jiangyukun on 2016/12/1.
 */

//节点审核
export const FETCH_PATIENT_LIST = 'FETCH_PATIENT_LIST'
export const FETCH_PATIENT_INFO = 'FETCH_PATIENT_INFO'
export const UPDATE_AUDITING_STATE = 'UPDATE_AUDITING_STATE'
export const UPDATE_VISIT_CARD = 'UPDATE_VISIT_CARD'
export const UPDATE_NODE_AUDITING_REMARK = 'UPDATE_NODE_AUDITING_REMARK'
export const UPDATE_IS_COMPLETE_VISIT = 'UPDATE_IS_COMPLETE_VISIT'

// 医院管理
export const FETCH_HOSPITAL_MANAGE_LIST = 'FETCH_HOSPITAL_MANAGE_LIST'
export const FETCH_PROVINCE_LIST = 'FETCH_PROVINCE_LIST'
export const FETCH_CITY_LIST = 'FETCH_CITY_LIST'
export const ADD_HOSPITAL = 'ADD_HOSPITAL'
export const FETCH_HOSPITAL_INFO = 'FETCH_HOSPITAL_INFO'
export const UPDATE_HOSPITAL_INFO = 'UPDATE_HOSPITAL_INFO'
export const FETCH_CITY_MAX_SERIAL_NUMBER = 'FETCH_CITY_MAX_SERIAL_NUMBER'

//病人评分统计
export const FETCH_PATIENT_SITUATION_LIST = 'FETCH_PATIENT_SITUATION_LIST'



