/**
 * Created by jiangyukun on 2016/12/1.
 */

export const FETCH_HOSPITAL_MANAGE_LIST = 'FETCH_HOSPITAL_MANAGE_LIST'
export const FETCH_PROVINCE_LIST = 'FETCH_PROVINCE_LIST'
export const FETCH_CITY_LIST = 'FETCH_CITY_LIST'


export const FETCH_PATIENT_LIST = 'FETCH_PATIENT_LIST'
export const UPDATE_VISIT_CARD = 'UPDATE_VISIT_CARD'
export const UPDATE_NODE_AUDITING_REMARK = 'UPDATE_NODE_AUDITING_REMARK'
export const UPDATE_IS_COMPLETE_VISIT = 'UPDATE_IS_COMPLETE_VISIT'
